name: Cypress Tests
run-name: testing out GitHub Actions 🚀

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bingo-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: bingo-app

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: bingo-app
          build: npm run build
          start: npm run dev
          browser: chrome
          wait-on: 'http://localhost:3000'
        